# Generated by Django 3.0.5 on 2022-01-28 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='makeover',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('website', models.CharField(max_length=250)),
                ('description', models.TextField()),
                ('keyword', models.TextField()),
                ('i_email', models.EmailField(max_length=254)),
                ('fb', models.CharField(max_length=250)),
                ('tw', models.CharField(max_length=250)),
                ('yb', models.CharField(max_length=250)),
            ],
        ),
    ]
