# Generated by Django 3.0.5 on 2022-02-05 02:02

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=225)),
                ('customer_address', models.CharField(max_length=225)),
                ('customer_phone', models.CharField(max_length=225)),
                ('customer_created', models.DateField(default=django.utils.timezone.now)),
                ('customer_update', models.DateField(default=django.utils.timezone.now)),
            ],
        ),
    ]
