# Generated by Django 3.0.5 on 2022-02-02 02:29

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='supplier',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('supplier_name', models.CharField(max_length=225)),
                ('supplier_address', models.CharField(max_length=225)),
                ('supplier_phone', models.CharField(max_length=225)),
                ('supplier_created', models.DateField(default=django.utils.timezone.now)),
                ('supplier_updated', models.DateField(default=django.utils.timezone.now)),
            ],
        ),
    ]
