# Generated by Django 3.0.5 on 2022-01-31 07:54

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='admin_staff',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('admin_user', models.CharField(max_length=225)),
                ('admin_password', models.CharField(max_length=225)),
                ('admin_name', models.CharField(max_length=225)),
                ('admin_address', models.CharField(max_length=225)),
                ('admin_phone', models.CharField(max_length=225)),
                ('admin_group', models.CharField(max_length=225)),
                ('admin_date', models.DateField(default=django.utils.timezone.now)),
            ],
        ),
    ]
